apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app-python-deployment
  labels:
    app: ecommerce-app-python
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-app-python
  template:
    metadata:
      labels:
        app: ecommerce-app-python
    spec:
      containers:
      - name: ecommerce-app-python
        image: ecommerce_app_python:latest
        ports:
        - containerPort: 5000                                                                                    