apiVersion: v1
kind: Service
metadata:
  name: ecommerce-app-python-service
  labels:
    app: ecommerce-app-python
spec:
  type: LoadBalancer
  selector:
    app: ecommerce-app-python
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000



